name: ESLint
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '21 11 * * 0'

jobs:
  eslint:
    name: Run ESLint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      # 0) Empfohlener Node-Cache
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci --omit=optional

      # optional: falls du den SARIF-Formatter nicht schon als Dep hast
      - run: npm i -D @microsoft/eslint-formatter-sarif@latest

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: npx eslint . --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload ESLint results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
